export const LOAD_DELIVERY_BOYS_SUCCESS = "LOAD_DELIVERY_BOYS_SUCCESS";
export const LOAD_MANAGERS_SUCCESS = "LOAD_MANAGERS_SUCCESS";
export const CREATE_DELIVERY_BOY_SUCCESS = "CREATE_DELIVERY_BOY_SUCCESS";
export const UPDATE_DELIVERY_BOY_SUCCESS = "UPDATE_DELIVERY_BOY_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const DELETE_DELIVERY_BOY_OPTIMISTIC = "DELETE_DELIVERY_BOY_OPTIMISTIC";
